Repository naccoro/WASK-Android, pull requests merged in 2020-08, with the labels that each got.

#14 Feature/main activity view
  app/src/main/java/com/naccoro/wask/MainActivity.java
  app/src/main/java/com/naccoro/wask/MainContract.java
  app/src/main/res/drawable-hdpi/ic_card_white.png
  app/src/main/res/drawable-hdpi/ic_people.png
  app/src/main/res/drawable-mdpi/ic_card_white.png
  app/src/main/res/drawable-mdpi/ic_people.png
  app/src/main/res/drawable-xhdpi/ic_card_white.png
  app/src/main/res/drawable-xhdpi/ic_people.png
  app/src/main/res/drawable-xxhdpi/ic_card_white.png
  app/src/main/res/drawable-xxhdpi/ic_people.png
  app/src/main/res/drawable-xxxhdpi/ic_card_white.png
  app/src/main/res/drawable-xxxhdpi/ic_people.png
  app/src/main/res/drawable/bg_button_change.xml
  app/src/main/res/drawable/bg_layout_content.xml
  app/src/main/res/drawable/ic_bad.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_good.xml
  app/src/main/res/drawable/ic_main_logo.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#28 refactor: splash layout
  app/src/main/res/drawable/splash.xml
Labels: 🎁 refactor ↩️

#19 Feature/setting activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/naccoro/wask/MainContract.java
  app/src/main/java/com/naccoro/wask/customview/datepicker/DatePickerDialogFragment.java
  app/src/main/java/com/naccoro/wask/customview/datepicker/wheel/WheelDatePicker.java
  app/src/main/java/com/naccoro/wask/main/MainActivity.java
  app/src/main/java/com/naccoro/wask/main/MainContract.java
  app/src/main/java/com/naccoro/wask/main/MainPresenter.java
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
  app/src/main/java/com/naccoro/wask/setting/SettingContract.java
  app/src/main/java/com/naccoro/wask/setting/SettingPresenter.java
  app/src/main/java/com/naccoro/wask/splash/SplashActivity.java
  app/src/main/res/drawable-hdpi/ic_appbarback.png
  app/src/main/res/drawable-hdpi/ic_datepicker_ok.png
  app/src/main/res/drawable-hdpi/ic_datepicker_x.png
  app/src/main/res/drawable-mdpi/ic_appbarback.png
  app/src/main/res/drawable-mdpi/ic_datepicker_ok.png
  app/src/main/res/drawable-mdpi/ic_datepicker_x.png
  app/src/main/res/drawable-xhdpi/ic_appbarback.png
  app/src/main/res/drawable-xhdpi/ic_datepicker_ok.png
  app/src/main/res/drawable-xhdpi/ic_datepicker_x.png
  app/src/main/res/drawable-xxhdpi/ic_appbarback.png
  app/src/main/res/drawable-xxhdpi/ic_datepicker_ok.png
  app/src/main/res/drawable-xxhdpi/ic_datepicker_x.png
  app/src/main/res/drawable-xxxhdpi/ic_appbarback.png
  app/src/main/res/drawable-xxxhdpi/ic_datepicker_ok.png
  app/src/main/res/drawable-xxxhdpi/ic_datepicker_x.png
  app/src/main/res/drawable/ic_settingtoggle_blue.xml
  app/src/main/res/drawable/ic_settingtoggle_gray.xml
  app/src/main/res/drawable/selector_foregroundalert_switch.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_date_picker_dialog_list_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🐶 개선 ☀️

#25 Feature/room db
  app/build.gradle
  app/src/main/java/com/naccoro/wask/base/BaseDao.java
  app/src/main/java/com/naccoro/wask/replacement/WaskDatabaseManager.java
  app/src/main/java/com/naccoro/wask/replacement/model/ReplacementHistory.java
  app/src/main/java/com/naccoro/wask/replacement/repository/ReplacementHistoryDao.java
  app/src/main/java/com/naccoro/wask/replacement/repository/ReplacementHistoryRepository.java
  app/src/main/java/com/naccoro/wask/utils/DateUtils.java
  app/src/main/res/layout/activity_main2.xml
  app/src/test/java/com/naccoro/wask/DateUtilsTest.java
  build.gradle
Labels: 🐶 개선 ☀️, 🚪 문서 ⬅️

#33 Feature/main view modify
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/naccoro/wask/calendar/CalendarActivity.java
  app/src/main/java/com/naccoro/wask/calendar/CalendarContract.java
  app/src/main/java/com/naccoro/wask/calendar/CalendarPresenter.java
  app/src/main/java/com/naccoro/wask/main/MainActivity.java
  app/src/main/java/com/naccoro/wask/main/MainContract.java
  app/src/main/java/com/naccoro/wask/main/MainPresenter.java
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
  app/src/main/res/anim/slide_activity_fadein.xml
  app/src/main/res/anim/slide_activity_fadeout.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/date_picker_item.xml
  app/src/main/res/layout/fragment_date_picker_dialog_list_dialog.xml
  app/src/main/res/values/dimens.xml
Labels: 🎁 refactor ↩️, 🐶 개선 ☀️, 🚪 문서 ⬅️

#30 Feature/setting activity
  app/src/main/java/com/naccoro/wask/customview/datepicker/DatePickerDialogFragment.java
  app/src/main/java/com/naccoro/wask/customview/datepicker/wheel/WheelDatePicker.java
  app/src/main/java/com/naccoro/wask/customview/datepicker/wheel/WheelRecyclerView.java
  app/src/main/java/com/naccoro/wask/preferences/SettingPreferenceManager.java
  app/src/main/java/com/naccoro/wask/preferences/SharedPreferenceManager.java
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
  app/src/main/java/com/naccoro/wask/setting/SettingContract.java
  app/src/main/java/com/naccoro/wask/setting/SettingPresenter.java
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_replacelater.xml
  app/src/main/res/layout/dialog_replacementcycle.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 개선 ☀️

#39 fix: 액티비티 종료시 전환효과 수정
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
Labels: 🎁 refactor ↩️, 🦋 버그잡자 🐱

#37 fix: Presenter에서 View 참조 방식 변경
  app/src/main/java/com/naccoro/wask/calendar/CalendarPresenter.java
  app/src/main/java/com/naccoro/wask/main/MainPresenter.java
  app/src/main/java/com/naccoro/wask/setting/SettingPresenter.java
Labels: 🎁 refactor ↩️

#42 Feature/notification
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/naccoro/wask/WaskApplication.java
  app/src/main/java/com/naccoro/wask/main/MainPresenter.java
  app/src/main/java/com/naccoro/wask/notification/WaskService.java
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
  app/src/main/java/com/naccoro/wask/setting/SettingContract.java
  app/src/main/java/com/naccoro/wask/setting/SettingPresenter.java
  app/src/main/res/drawable-anydpi-v24/ic_notification_logo.xml
  app/src/main/res/drawable-hdpi/ic_notification_logo.png
  app/src/main/res/drawable-mdpi/ic_notification_logo.png
  app/src/main/res/drawable-xhdpi/ic_notification_logo.png
  app/src/main/res/drawable-xxhdpi/ic_notification_logo.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: 🐶 개선 ☀️

#43 Feature/push alert
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/naccoro/wask/WaskApplication.java
  app/src/main/java/com/naccoro/wask/calendar/CalendarActivity.java
  app/src/main/java/com/naccoro/wask/main/MainActivity.java
  app/src/main/java/com/naccoro/wask/main/MainContract.java
  app/src/main/java/com/naccoro/wask/main/MainPresenter.java
  app/src/main/java/com/naccoro/wask/mock/MockDatabase.java
  app/src/main/java/com/naccoro/wask/notification/PushNotificationService.java
  app/src/main/java/com/naccoro/wask/preferences/SettingPreferenceManager.java
  app/src/main/java/com/naccoro/wask/receivers/AlarmReceiver.java
  app/src/main/java/com/naccoro/wask/receivers/BootReceiver.java
  app/src/main/java/com/naccoro/wask/receivers/ReplaceLaterReceiver.java
  app/src/main/java/com/naccoro/wask/receivers/ReplaceMaskReceiver.java
  app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
  app/src/main/java/com/naccoro/wask/setting/SettingContract.java
  app/src/main/java/com/naccoro/wask/setting/SettingPresenter.java
  app/src/main/java/com/naccoro/wask/utils/AlarmUtil.java
  app/src/main/java/com/naccoro/wask/utils/DateUtils.java
  app/src/main/java/com/naccoro/wask/utils/NotificationUtil.java
  app/src/main/res/drawable/ic_notification_logo.xml
  app/src/main/res/drawable/ic_wask_logo.xml
  app/src/main/res/layout/notification_replacementcycle.xml
  app/src/main/res/layout/notification_replacemlater.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 개선 ☀️, 🚪 문서 ⬅️
